server:
  port: 8080

spring:
  application:
    name: dubbo-producer
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.1.221:2181
  protocol:
    port: -1
    name: dubbo
